\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Jx2371-p8131-hw4},
            pdfauthor={Jingyu Xu},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{longtable,booktabs}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Jx2371-p8131-hw4}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Jingyu Xu}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{3/4/2019}


\begin{document}
\maketitle

\subsection{Data manipulation}\label{data-manipulation}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data1 =}\StringTok{ }\KeywordTok{tibble}\NormalTok{(}
  \DataTypeTok{low_satisfaction =} \KeywordTok{c}\NormalTok{(}\DecValTok{65}\NormalTok{, }\DecValTok{34}\NormalTok{, }\DecValTok{130}\NormalTok{, }\DecValTok{141}\NormalTok{, }\DecValTok{67}\NormalTok{, }\DecValTok{130}\NormalTok{),}
  \DataTypeTok{medium_satisfaction =} \KeywordTok{c}\NormalTok{(}\DecValTok{54}\NormalTok{, }\DecValTok{47}\NormalTok{, }\DecValTok{76}\NormalTok{, }\DecValTok{116}\NormalTok{, }\DecValTok{48}\NormalTok{, }\DecValTok{105}\NormalTok{),}
  \DataTypeTok{high_satisfaction =} \KeywordTok{c}\NormalTok{(}\DecValTok{100}\NormalTok{, }\DecValTok{100}\NormalTok{, }\DecValTok{111}\NormalTok{, }\DecValTok{191}\NormalTok{, }\DecValTok{62}\NormalTok{, }\DecValTok{104}\NormalTok{),}
  \DataTypeTok{type_of_housing =} \KeywordTok{c}\NormalTok{(}\StringTok{'tower_block'}\NormalTok{, }\StringTok{'tower_block'}\NormalTok{, }\StringTok{'apartment'}\NormalTok{, }\StringTok{'apartment'}\NormalTok{, }\StringTok{'house'}\NormalTok{, }\StringTok{'house'}\NormalTok{),}
  \DataTypeTok{contact =} \KeywordTok{rep}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\StringTok{'low'}\NormalTok{, }\StringTok{'high'}\NormalTok{), }\DecValTok{3}\NormalTok{)}
\NormalTok{)}

\NormalTok{data1}\OperatorTok{$}\NormalTok{contact=}\KeywordTok{factor}\NormalTok{(data1}\OperatorTok{$}\NormalTok{contact, }\DataTypeTok{levels=}\KeywordTok{c}\NormalTok{(}\StringTok{'low'}\NormalTok{,}\StringTok{'high'}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\subsection{i)percentage table}\label{ipercentage-table}

\paragraph{1)corresponding to contact with other
residents}\label{corresponding-to-contact-with-other-residents}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{##print the table corresponding to contact with others}
\NormalTok{data_contact =}\StringTok{ }\NormalTok{data1}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(contact)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{low=}\KeywordTok{sum}\NormalTok{(low_satisfaction), }\DataTypeTok{medium=}\KeywordTok{sum}\NormalTok{(medium_satisfaction), }\DataTypeTok{high =} \KeywordTok{sum}\NormalTok{(high_satisfaction))}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{total =}\NormalTok{ low}\OperatorTok{+}\NormalTok{medium}\OperatorTok{+}\NormalTok{high)}

\NormalTok{data_contact}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{low =} \KeywordTok{percent}\NormalTok{(low}\OperatorTok{/}\NormalTok{total), }\DataTypeTok{medium =} \KeywordTok{percent}\NormalTok{(medium}\OperatorTok{/}\NormalTok{total), }\DataTypeTok{high =} \KeywordTok{percent}\NormalTok{(high}\OperatorTok{/}\NormalTok{total))}\OperatorTok{%>%}
\StringTok{  }\NormalTok{knitr}\OperatorTok{::}\KeywordTok{kable}\NormalTok{(}\DataTypeTok{col.names =} \KeywordTok{c}\NormalTok{(}\StringTok{"type of contact"}\NormalTok{, }\StringTok{"low satisfaction"}\NormalTok{,}\StringTok{"medium satisfaction"}\NormalTok{,}\StringTok{"high satisfaction"}\NormalTok{,}\StringTok{"total"}\NormalTok{ ))}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrrrr@{}}
\toprule
type of contact & low satisfaction & medium satisfaction & high
satisfaction & total\tabularnewline
\midrule
\endhead
low & 36.75\% & 24.96\% & 38.29\% & 713\tabularnewline
high & 31.51\% & 27.69\% & 40.81\% & 968\tabularnewline
\bottomrule
\end{longtable}

From the table above, we can observe that the people who have high
degree of contact with other residents also have higher proportion of
high level satisfaction, compared with those who have low degree of
contact. Meanwhile, among the two groups of poeple divided by the degree
of contact with others, the largest proportions of them have high
satisfaction, and the lowes proportions of them have medium
satisfaction.

\paragraph{2)corresponding to types of
housing}\label{corresponding-to-types-of-housing}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{##Print the table corresponding to type of housing}
\NormalTok{data_type =}\StringTok{ }\NormalTok{data1}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{group_by}\NormalTok{(type_of_housing)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{low=}\KeywordTok{sum}\NormalTok{(low_satisfaction), }\DataTypeTok{medium=}\KeywordTok{sum}\NormalTok{(medium_satisfaction), }\DataTypeTok{high =} \KeywordTok{sum}\NormalTok{(high_satisfaction))}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{total =}\NormalTok{ low}\OperatorTok{+}\NormalTok{medium}\OperatorTok{+}\NormalTok{high)}

\NormalTok{data_type}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{low =} \KeywordTok{percent}\NormalTok{(low}\OperatorTok{/}\NormalTok{total), }\DataTypeTok{medium =} \KeywordTok{percent}\NormalTok{(medium}\OperatorTok{/}\NormalTok{total), }\DataTypeTok{high =} \KeywordTok{percent}\NormalTok{(high}\OperatorTok{/}\NormalTok{total))}\OperatorTok{%>%}
\StringTok{  }\NormalTok{knitr}\OperatorTok{::}\KeywordTok{kable}\NormalTok{(}\DataTypeTok{col.names =} \KeywordTok{c}\NormalTok{(}\StringTok{"type of housing"}\NormalTok{, }\StringTok{"low satisfaction"}\NormalTok{,}\StringTok{"medium satisfaction"}\NormalTok{,}\StringTok{"high satisfaction"}\NormalTok{,}\StringTok{"total"}\NormalTok{ ))}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrrrr@{}}
\toprule
type of housing & low satisfaction & medium satisfaction & high
satisfaction & total\tabularnewline
\midrule
\endhead
apartment & 35.42\% & 25.10\% & 39.48\% & 765\tabularnewline
house & 38.18\% & 29.65\% & 32.17\% & 516\tabularnewline
tower\_block & 24.75\% & 25.25\% & 50.00\% & 400\tabularnewline
\bottomrule
\end{longtable}

From the table above, we can observe that the people who live in tower
block have largest proportions of high satisfaction, about 50\%. And the
people who live in house have the lowest proportions of high
satisfaction. Meanwhile, we can see that among people who live in
apartment, the largest proportions of them have high satisfaction. By
contrast, among people who live in house, the largest proportions of
them have low satisfaction.

\subsection{ii）nominal logistic regression
model}\label{iinominal-logistic-regression-model}

\paragraph{analyze the association from the nominal
model}\label{analyze-the-association-from-the-nominal-model}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{nominal_fit =}\StringTok{ }\KeywordTok{multinom}\NormalTok{(}\KeywordTok{cbind}\NormalTok{(low_satisfaction, medium_satisfaction, high_satisfaction)}\OperatorTok{~}\NormalTok{contact}\OperatorTok{+}\NormalTok{type_of_housing,}\DataTypeTok{data=}\NormalTok{data1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # weights:  15 (8 variable)
## initial  value 1846.767257 
## iter  10 value 1802.866981
## final  value 1802.740161 
## converged
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(nominal_fit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Call:
## multinom(formula = cbind(low_satisfaction, medium_satisfaction, 
##     high_satisfaction) ~ contact + type_of_housing, data = data1)
## 
## Coefficients:
##                     (Intercept) contacthigh type_of_housinghouse
## medium_satisfaction -0.51401706   0.2959796           0.06967794
## high_satisfaction   -0.08082309   0.3282256          -0.30401939
##                     type_of_housingtower_block
## medium_satisfaction                  0.4067570
## high_satisfaction                    0.6415915
## 
## Std. Errors:
##                     (Intercept) contacthigh type_of_housinghouse
## medium_satisfaction   0.1207955   0.1301045            0.1437749
## high_satisfaction     0.1079357   0.1181870            0.1351693
##                     type_of_housingtower_block
## medium_satisfaction                  0.1713008
## high_satisfaction                    0.1500773
## 
## Residual Deviance: 3605.48 
## AIC: 3621.48
\end{verbatim}

Summary of the coefficients(interpretation):

The log odds ratio of medium satisfaction versus low satisfaction
between high and low level of contact with other residents is 0.2960.
The log odds ratio of high satisfaction versus low satisfaction between
high and low level of contact with other residents is 0.3282. Noticing
the people of high contact have higher odds ratio, which indicates that
they have higher level of satisfaction.

The log odds ratio of medium satisfaction versus low satisfaction
between people who live in house and apartment is 0.0697. The log odds
ratio of medium satisfaction versus low satisfaction between people who
live in tower block and apartment is 0.4068. The log odds ratio of high
satisfaction versus low satisfaction between people who live in house
and apartment is -0.3040. The log odds ratio of high satisfaction versus
low satisfaction between people who live in tower block and apartment is
-0.6416. This indicates that residents who live in tower blocks have the
highest level of satisfaction.

\paragraph{Table of Coefficient
interval}\label{table-of-coefficient-interval}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{##95%CI}
\NormalTok{data_combine =}\StringTok{ }\NormalTok{data1}\OperatorTok{%>%}
\KeywordTok{gather}\NormalTok{(}\DataTypeTok{key =} \StringTok{'satisfaction'}\NormalTok{, }\DataTypeTok{value =} \StringTok{'proportion'}\NormalTok{, low_satisfaction}\OperatorTok{:}\NormalTok{high_satisfaction)}

\KeywordTok{multinom}\NormalTok{(satisfaction}\OperatorTok{~}\NormalTok{contact}\OperatorTok{+}\NormalTok{type_of_housing, }\DataTypeTok{weights =}\NormalTok{ proportion,}\DataTypeTok{data=}\NormalTok{data_combine)}\OperatorTok{%>%}\StringTok{ }
\NormalTok{broom}\OperatorTok{::}\KeywordTok{tidy}\NormalTok{()}\OperatorTok{%>%}\StringTok{ }
\KeywordTok{filter}\NormalTok{(term }\OperatorTok{!=}\StringTok{ '(Intercept)'}\NormalTok{) }\OperatorTok{%>%}\StringTok{ }
\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{CI_Low =}\NormalTok{ estimate }\OperatorTok{*}\StringTok{ }\KeywordTok{exp}\NormalTok{(std.error }\OperatorTok{*}\StringTok{ }\KeywordTok{qnorm}\NormalTok{(}\FloatTok{0.025}\NormalTok{)),}
\DataTypeTok{CI_High =}\NormalTok{ estimate }\OperatorTok{/}\StringTok{ }\KeywordTok{exp}\NormalTok{(std.error }\OperatorTok{*}\StringTok{ }\KeywordTok{qnorm}\NormalTok{(}\FloatTok{0.025}\NormalTok{)))}\OperatorTok{%>%}
\KeywordTok{select}\NormalTok{(y.level, term, CI_Low, CI_High)}\OperatorTok{%>%}
\NormalTok{knitr}\OperatorTok{::}\KeywordTok{kable}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # weights:  15 (8 variable)
## initial  value 1846.767257 
## iter  10 value 1803.035474
## final  value 1802.740161 
## converged
\end{verbatim}

\begin{longtable}[]{@{}llrr@{}}
\toprule
y.level & term & CI\_Low & CI\_High\tabularnewline
\midrule
\endhead
low\_satisfaction & contacthigh & 0.5712847 & 0.9079345\tabularnewline
low\_satisfaction & type\_of\_housinghouse & 1.0398692 &
1.7664093\tabularnewline
low\_satisfaction & type\_of\_housingtower\_block & 0.3922958 &
0.7064895\tabularnewline
medium\_satisfaction & contacthigh & 0.7550285 &
1.2417410\tabularnewline
medium\_satisfaction & type\_of\_housinghouse & 1.0926031 &
1.9325471\tabularnewline
medium\_satisfaction & type\_of\_housingtower\_block & 0.5845810 &
1.0695056\tabularnewline
\bottomrule
\end{longtable}

The 95\% coefficient interval is caculated in the table. \#\#\#\#Check
goodness of fit:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pihat=}\KeywordTok{predict}\NormalTok{(nominal_fit,}\DataTypeTok{type=}\StringTok{'probs'}\NormalTok{) }
\NormalTok{m=}\KeywordTok{rowSums}\NormalTok{(data1[,}\DecValTok{1}\OperatorTok{:}\DecValTok{3}\NormalTok{])}
\NormalTok{res.pearson=(data1[,}\DecValTok{1}\OperatorTok{:}\DecValTok{3}\NormalTok{]}\OperatorTok{-}\NormalTok{pihat}\OperatorTok{*}\NormalTok{m)}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(pihat}\OperatorTok{*}\NormalTok{m) }\CommentTok{# pearson residuals }
\NormalTok{G.stat=}\KeywordTok{sum}\NormalTok{(res.pearson}\OperatorTok{^}\DecValTok{2}\NormalTok{) }\CommentTok{# Generalized Pearson Chisq Stat}
\NormalTok{G.stat}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 6.932335
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pval=}\DecValTok{1}\OperatorTok{-}\KeywordTok{pchisq}\NormalTok{(G.stat,}\DataTypeTok{df=}\NormalTok{(}\DecValTok{6}\OperatorTok{-}\DecValTok{4}\NormalTok{)}\OperatorTok{*}\NormalTok{(}\DecValTok{3}\OperatorTok{-}\DecValTok{1}\NormalTok{))}
\NormalTok{pval}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1395075
\end{verbatim}

The Pvalue is 0.1395075, which is larger than 0.05, indicating the null
hypothesis cannot be rejected. Thus, we can conclude that the fit is
good.

\subsection{iii)proportional odds
model}\label{iiiproportional-odds-model}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data_combine}\OperatorTok{$}\NormalTok{satisfaction=}\KeywordTok{factor}\NormalTok{(data_combine}\OperatorTok{$}\NormalTok{satisfaction, }\DataTypeTok{levels=}\KeywordTok{c}\NormalTok{(}\StringTok{'low_satisfaction'}\NormalTok{,}\StringTok{'medium_satisfaction'}\NormalTok{,}\StringTok{'high_satisfaction'}\NormalTok{))}

\NormalTok{fit_polr =}\StringTok{ }\NormalTok{MASS}\OperatorTok{::}\KeywordTok{polr}\NormalTok{(satisfaction}\OperatorTok{~}\NormalTok{contact}\OperatorTok{+}\NormalTok{type_of_housing, }\DataTypeTok{weights =}\NormalTok{ proportion,}\DataTypeTok{data=}\NormalTok{data_combine)}

\KeywordTok{summary}\NormalTok{(fit_polr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Re-fitting to get Hessian
\end{verbatim}

\begin{verbatim}
## Call:
## MASS::polr(formula = satisfaction ~ contact + type_of_housing, 
##     data = data_combine, weights = proportion)
## 
## Coefficients:
##                              Value Std. Error t value
## contacthigh                 0.2524    0.09306   2.713
## type_of_housinghouse       -0.2353    0.10521  -2.236
## type_of_housingtower_block  0.5010    0.11675   4.291
## 
## Intercepts:
##                                       Value   Std. Error t value
## low_satisfaction|medium_satisfaction  -0.4964  0.0897    -5.5356
## medium_satisfaction|high_satisfaction  0.6161  0.0901     6.8381
## 
## Residual Deviance: 3610.286 
## AIC: 3620.286
\end{verbatim}

Contact with others: The odds ratio between high and low levels of
contact is 0.2524, so people with higher level of contact with other
residents have higher level of satisfaction.

Types of housing: The odds ratio between people living in house versus
people living in apartment is -0.2353. The odds ratio between people
living in tower block versus apartment is 0.5010. It indicates that
people living in house have the lowest proportion of satisfaction and
people living in tower block have the highest proportion of
satisfaction.

\subsection{iv)Pearson residuals}\label{ivpearson-residuals}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pihat=}\KeywordTok{predict}\NormalTok{(fit_polr,data_combine,}\DataTypeTok{type=}\StringTok{'p'}\NormalTok{)}
\NormalTok{m=}\KeywordTok{rowSums}\NormalTok{(data1[,}\DecValTok{1}\OperatorTok{:}\DecValTok{3}\NormalTok{])}
\NormalTok{res.pearson=(data1[,}\DecValTok{1}\OperatorTok{:}\DecValTok{3}\NormalTok{]}\OperatorTok{-}\NormalTok{pihat}\OperatorTok{*}\NormalTok{m)}\OperatorTok{/}\KeywordTok{sqrt}\NormalTok{(pihat}\OperatorTok{*}\NormalTok{m)}
\NormalTok{residual_matrix =}\StringTok{ }\KeywordTok{cbind}\NormalTok{(data1}\OperatorTok{$}\NormalTok{type_of_housing,data1}\OperatorTok{$}\NormalTok{contact,res.pearson)}
\NormalTok{residual_matrix}\OperatorTok{%>%}\NormalTok{knitr}\OperatorTok{::}\KeywordTok{kable}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}llrrr@{}}
\toprule
data1\$type\_of\_housing & data1\$contact & low\_satisfaction &
medium\_satisfaction & high\_satisfaction\tabularnewline
\midrule
\endhead
tower\_block & low & 0.7793895 & -0.6525338 & 5.3355092\tabularnewline
tower\_block & high & -0.9946675 & 1.0527519 & 9.3999230\tabularnewline
apartment & low & 0.9176664 & -4.0128725 & -0.8171528\tabularnewline
apartment & high & -0.2369928 & -2.3214675 & 3.9319564\tabularnewline
house & low & -1.1408779 & -3.3059610 & -1.7106366\tabularnewline
house & high & 0.2742748 & -1.9449014 & -2.0336685\tabularnewline
\bottomrule
\end{longtable}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{max_residual =}\StringTok{ }\NormalTok{residual_matrix[,}\DecValTok{3}\OperatorTok{:}\DecValTok{5}\NormalTok{]}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{abs}\NormalTok{()}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{max}\NormalTok{()}
\NormalTok{max_residual}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9.399923
\end{verbatim}

From the results above, the largest pearson residuals belong to ``high
satisfaction''" and covariates of high contact and tower block. It is
9.400.


\end{document}
